kind = "web"
previewPath = "/"
title = "Enzora"
version = "1.0.0"
id = "artifacts/enzora"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24869

[services.development]
run = "pnpm --filter @workspace/enzora run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/enzora", "run", "build" ]
publicDir = "artifacts/enzora/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24869"
BASE_PATH = "/"
