import { pgTable, serial, text, integer, numeric, timestamp } from "drizzle-orm/pg-core";

export const ordersTable = pgTable("orders", {
  id: serial("id").primaryKey(),
  orderReference: text("order_reference").notNull().unique(),
  fullName: text("full_name").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull(),
  countryCity: text("country_city").notNull(),
  country: text("country"),
  city: text("city"),
  customerType: text("customer_type").notNull(),
  productSelection: text("product_selection").notNull().default("bandage_pack"),
  quantity: integer("quantity").notNull(),
  productNameSnapshot: text("product_name_snapshot"),
  productPriceSnapshot: numeric("product_price_snapshot", { precision: 12, scale: 2 }),
  productCurrencySnapshot: text("product_currency_snapshot"),
  totalEstimatedPrice: numeric("total_estimated_price", { precision: 14, scale: 2 }),
  message: text("message"),
  status: text("status").notNull().default("new"),
  trackingStage: text("tracking_stage").notNull().default("order_submitted"),
  trackingLocation: text("tracking_location"),
  trackingNote: text("tracking_note"),
  paymentMethod: text("payment_method"),
  paymentStatus: text("payment_status").notNull().default("pending"),
  paymentNote: text("payment_note"),
  paymentReference: text("payment_reference"),
  amountDue: numeric("amount_due", { precision: 14, scale: 2 }),
  currency: text("currency").notNull().default("USD"),
  paidAt: timestamp("paid_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export type OrderRow = typeof ordersTable.$inferSelect;
